name: Run check

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    name: Run checks
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: release script
        run: npm prepare
